# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Framework-MIDI
version:      0.04
version_from: lib/POE/Framework/MIDI.pm
installdirs:  site
requires:
    MIDI::Simple:                  0
    POE:                           0.29

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
